name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: bats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install bats
        run: npm install bats@1.11.0

      - name: Run tests
        run: npm exec -- bats test/*.bats
